config/routes.rb
Atualidadesweb::Application.routes.draw do

  resources :timeline

  namespace :admin do
    resources :feeds
  end

  root :to => 'timeline#index'

end

app/models/feed_repository.rb
require 'yaml'

class FeedRepository
  def initialize(path)
    @feeds = YAML.load_file path
  end

  def all
    @feeds
  end
end

app/models/news.rb
class News
  include MongoMapper::Document

  LIMIT = 130

  timestamps!
  belongs_to :feed

  key :url, String
  key :title, String
  key :subtitle, String
  key :image, String
  key :featured_level, Integer

  def self.build_with(options)
    where(url: options[:url]).first_or_create(options) if valid? options
  end

  def self.breaking_news
    @breaking_news ||= self.all(limit: LIMIT, order: :created_at.desc)
    @breaking_news.shuffle
  end

  def self.destroy_old_news
    total_news = News.count
    if total_news > LIMIT
      old_news = self.all(limit: News.count - LIMIT, order: :created_at.asc)
      old_news.each { |o| o.destroy }
    end
  end

  private
  def self.valid?(options)
    options[:title] || options[:subtitle]
  end

end

app/models/news_feed.rb
class NewsFeed
  include MongoMapper::Document

  key :host, String
  key :selector, String
  key :url_pattern, String
  key :title, String
  key :subtitle, String
  key :image_source, String
  key :date_tag, String

  validates :selector, :url_pattern, :title, :subtitle, :presence => true
  validates :host, :format => URI::regexp(%w(http https)), :presence => true

  def fetch(reader)
    reader.new(@host).highlights(
                                  selector: @selector,
                                  href: @url_pattern,
                                  title: @title,
                                  subtitle: @subtitle,
                                  img: @image_source,
                                  date: @date_tag,
                                  host: @host
                                  )
  end

end

app/models/news_updater.rb
require 'newly'
require 'cache'

class NewsUpdater
  def update_by(feeds)
    Cache.fetch(key: 'featured') do
      Thread.new { News.destroy_old_news }
      feeds.each do |feed|
        Thread.new { Newlt::NewsCrawler.new(url: feed['url'], feed: feed).fetch }
      end
    end
  end
end

app/models/reader.rb
require 'nokogiri'
require 'open-uri'
class Reader

  attr_reader :title, :selector, :url

  def initialize(feed, selector=Nokogiri::HTML(open(feed.url)))
    @feed = feed
    @selector = selector
    @title = @selector.at_css("title").text
  end

  def news
    news = []
    limit = @feed.limit
    @selector.css(@feed.selector).first(limit).each {|item| news << build_news_by(item)}
    news
  end

private
  def build_news_by(item)
    if (item)
      level = @feed.featured_level
      title = find_text(item, @feed.title)
      subtitle = find_text(item, @feed.subtitle)
      img = find_image(item, @feed.image_source)
      href = find_link(item, @feed.url_pattern, 'href')

      if @feed.host
        href = "#{@feed.host}/#{href}".gsub('../', '') if href && !href.include?('http')
        img = "#{@feed.host}/#{img}".gsub('../', '') if img && img.include?('../')
      end

      # creating news
      News.new(feed: @feed, url: href, title: title, subtitle: subtitle, image: img, featured_level: level)
    end
  end

  def find_image(item, image_source)
    image = find_link(item, image_source, 'src')
    if (image && image.include?("==/"))
      image = "http://#{image.split("==/").last}"
    end
    image
  end

  def find_link(item, element, src)
    item.css(element).map { |doc| doc[src] }.first if valid?(element)
  end

  def find_text(item, element)
    item.css(element).text if valid?(element)
  end

  def valid?(element)
    element && !element.empty?
  end

end

app/models/timeline.rb
class Timeline

  def initialize(repository, news_updater)
    @repository = repository
    @news_updater = news_updater
  end

  def featured_news
    Thread.new { @news_updater.update_by @repository.all }
    @featured_news ||= Cache.fetch(key: 'breaking_news') { News.breaking_news }
  end

end

app/models/web_reader.rb
require 'nokogiri'
require 'open-uri'
class WebReader

  attr_reader :title, :selector, :url

  def initialize(feed, selector=Nokogiri::HTML(open(feed.url)))
    @feed = feed
    @selector = selector
    @title = @selector.at_css("title").text
  end

  def news
    news = []
    limit = @feed.limit
    @selector.css(@feed.selector).first(limit).each {|item| news << build_news_by(item)}
    news
  end

private
  def build_news_by(item)
    if (item)
      level = @feed.featured_level
      title = find_text(item, @feed.title)
      subtitle = find_text(item, @feed.subtitle)
      img = find_image(item, @feed.image_source)
      href = find_link(item, @feed.url_pattern, 'href')

      if @feed.host
        href = "#{@feed.host}/#{href}".gsub('../', '') if href && !href.include?('http')
        img = "#{@feed.host}/#{img}".gsub('../', '') if img && img.include?('../')
      end

      # creating news
      News.new(feed: @feed, url: href, title: title, subtitle: subtitle, image: img, featured_level: level)
    end
  end

  def find_image(item, image_source)
    image = find_link(item, image_source, 'src')
    if (image && image.include?("==/"))
      image = "http://#{image.split("==/").last}"
    end
    image
  end

  def find_link(item, element, src)
    item.css(element).map { |doc| doc[src] }.first if valid?(element)
  end

  def find_text(item, element)
    item.css(element).text if valid?(element)
  end

  def valid?(element)
    element && !element.empty?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  respond_to :html, :json

  def index
    @feeds = Feed.all
    respond_with(@feeds)
  end

  def show
    @feed = Feed.find(params[:id])
    @news = @feed.fetch(Reader.new(@feed.url))
    respond_with(@feed)
  end

  def new
    @feed = Feed.new
    respond_with(@feed)
  end

  def edit
    @feed = Feed.find(params[:id])
    respond_with(@feed)
  end

  def create
    @feed = Feed.new(params[:feed])
    flash[:notice] = 'Feed was successfully created.' if @feed.save
    respond_with(@feed, location: @feed)
  end

  def update
    @feed = Feed.find(params[:id])
    flash[:notice] = 'Feed was successfully updated.' if @feed.update_attributes(params[:feed])
    respond_with(@feed, location: @feed)
  end

  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy
    respond_with(nil, :location => feeds_url)
  end
end

app/controllers/timeline_controller.rb
class TimelineController < ApplicationController
  respond_to :html, :json
  def index
    repository = FeedRepository.new('feeds.yml')
    timeline = Timeline.new(repository, NewsUpdater.new)
    @news = timeline.featured_news
    respond_with @news
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/timeline_helper.rb
module TimelineHelper
end

app/views/admin/feeds/_form.html.erb
<%= form_for [:admin, @feed] do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <label><%= f.label :favicon %></label>
  <%= f.text_field :favicon, :class => 'input-xxlarge' %>

  <label><%= f.label :selector %></label>
  <%= f.text_field :selector, :class => 'input-xxlarge' %>

  <label><%= f.label :featured_level %></label>
  <%= f.number_field :featured_level, :type => "number" %>

  <label><%= f.label :limit %></label>
  <%= f.text_field :limit, :type => "number" %>

  <label><%= f.label :url %></label>
  <%= f.text_field :url %>

  <label><%= f.label :host %></label>
  <%= f.text_field :host %>

  <label><%= f.label :url_pattern %></label>
  <%= f.text_field :url_pattern %>

  <label><%= f.label :title %></label>
  <%= f.text_field :title %>

  <label><%= f.label :subtitle %></label>
  <%= f.text_field :subtitle %>

  <label><%= f.label :image_source %></label>
  <%= f.text_field :image_source %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_feed_path(@feed) %> |
<%= link_to 'Back', admin_feeds_path %>

app/views/admin/feeds/index.html.erb
<h1>Listing feeds</h1>

<table class="table table-bordered table-striped">
  <tr>
    <th>Featured Level</th>
    <th>Url</th>
    <th>Selector</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feeds.each do |feed| %>
  <tr>
    <td><%= feed.featured_level %></td>
    <td><%= feed.url %></td>
    <td><%= feed.selector %></td>
    <td><%= link_to 'Show', admin_feed_path(feed) %></td>
    <td><%= link_to 'Edit', edit_admin_feed_path(feed) %></td>
    <td><%= link_to 'Destroy', admin_feed_path(feed), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New', new_admin_feed_path %>

app/views/admin/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_feeds_path %>

app/views/admin/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>favicon:</b>
  <%= image_tag(@feed.favicon) %>
</p>

<p>
  <b>Url:</b>
  <%= @feed.url %>
</p>

<p>
  <b>Selector:</b>
  <%= @feed.selector %>
</p>

<p>
  <b>Url pattern:</b>
  <%= @feed.url_pattern %>
</p>

<p>
  <b>Title:</b>
  <%= @feed.title %>
</p>

<p>
  <b>Subtitle:</b>
  <%= @feed.subtitle %>
</p>

<p>
  <b>Image source:</b>
  <%= @feed.image_source %>
</p>

<p>
  <b>Host:</b>
  <%= @feed.host %>
</p>

<fieldset>
  <p><%= "Tempo de resposta: #{@response_time}s" %>
  <%= link_to 'Edit', edit_admin_feed_path(@feed) %> |
  <%= link_to 'Back', admin_feeds_path %>
  <legend>Preview</legend>
  <ul>
    <% @news.each do |n| %>
      <% if n %>
        <li>
          <a href="<%= n.url %>" target="_blank">
            <% if n.image %>
              <img class="image-news" src="<%= n.image %>">
            <% end %>
            <% if n.title %>
              <span class="title-news"><%= n.title %></span>
            <% end %>
            <% if n.subtitle && n.subtitle != n.title %>
              <span class="title-news"><%= n.subtitle %></span>
            <% else %>
              <span class="subtitle-news"><%= n.subtitle %></span>
            <% end %>
          </a>
        </li>
      <% end %>
    <% end %>
  </ul>
</fieldset>

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :selector %><br />
    <%= f.text_field :selector %>
  </div>
  <div class="field">
    <%= f.label :url_pattern %><br />
    <%= f.text_field :url_pattern %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br />
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :image_source %><br />
    <%= f.text_field :image_source %>
  </div>
  <div class="field">
    <%= f.label :date_tag %><br />
    <%= f.text_field :date_tag %>
  </div>
  <div class="field">
    <%= f.label :host %><br />
    <%= f.text_field :host %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @feed.url %>
</p>

<p>
  <b>Selector:</b>
  <%= @feed.selector %>
</p>

<p>
  <b>Url pattern:</b>
  <%= @feed.url_pattern %>
</p>

<p>
  <b>Title:</b>
  <%= @feed.title %>
</p>

<p>
  <b>Subtitle:</b>
  <%= @feed.subtitle %>
</p>

<p>
  <b>Image source:</b>
  <%= @feed.image_source %>
</p>

<p>
  <b>Date tag:</b>
  <%= @feed.date_tag %>
</p>

<p>
  <b>Host:</b>
  <%= @feed.host %>
</p>

<fieldset>
  <%= link_to 'Edit', edit_feed_path(@feed) %> |
  <%= link_to 'Back', feeds_path %>
  <legend>Preview</legend>
  <ul>
    <% @news.each do |n| %>
      <li>
        <a href="<%= n.url %>" target="_blank">
          <time><%= n.date %></time>
          <% if n.image %>
            <img class="image-news" src="<%= n.image %>">
          <% end %>
          <% if n.title %>
            <span class="title-news"><%= n.title %></span>
          <% end %>
          <% if n.subtitle && n.subtitle != n.title %>
            <span class="title-news"><%= n.subtitle %></span>
          <% else %>
            <span class="subtitle-news"><%= n.subtitle %></span>
          <% end %>
        </a>
      </li>
    <% end %>
  </ul>
</fieldset>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Atualidades|Web</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'bootstrap', 'admin' %>
  <%= csrf_meta_tags %>
</head>
  <body>
	<!--[if lt IE 7]>
        <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
    <![endif]-->

  	<div class="area">
          <nav class="navbar">
              <div class="navbar-inner">
                  <a class="brand" href="#">Notícias</a>
                  <ul class="nav">
                    <li class="active"><a href="index.html">Início</a></li>
                    <li><a href="#">Esportes</a></li>
                    <li><a href="#">Mundo</a></li>
                  </ul>
              </div>
          </nav>
          <div class="separator"></div>
          <%= yield %>
    </div>
    <script type="text/javascript">
        <%= yield :javascript %>
    </script>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Atualidades|Web</title>
  <meta name="viewport" content="height=device-height, width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
  <meta name="author" content="Atualidades|Web"/>
  <meta name="description" content="As principais notícias do Brasil e do mundo estão por aqui!
" />
  <meta name="keywords" content="atualidades, web, noticias, news, breaking, brasil, brazil, mundo, world, economia, esporte, lazer, entretenimento, politica, cultura" />
  <%= stylesheet_link_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>
  <body>
	<!--[if lt IE 7]>
        <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
    <![endif]-->

  	<div class="area">
          <nav class="navbar">
              <div class="navbar-inner">
                  <a class="brand" href="#">Atualidades | Web</a>
                  <ul class="nav">
                    <li>
                      <div id="fb-like" class="fb-like" data-href="https://www.facebook.com/atualidadesweb" data-send="true" data-width="100" data-show-faces="true" data-layout="button_count" data-font="lucida grande" data-action="recommend"></div>
                    </li>
                    <!--li class="active"><a href="#">Início</a></li -->
                  </ul>
              </div>
          </nav>
          <div class="separator"></div>
          <%= yield %>
    </div>
    <footer></footer>
    <div id="fb-root"></div>
    <script type="text/javascript">
        <%= yield :javascript %>
    </script>
    <script type="text/javascript">
    // Google Analytics
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-38184587-1']);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

      // Facebook
      (function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1&appId=272370542894863";
            fjs.parentNode.insertBefore(js, fjs);
            d.getElementById('fb-like').style.marginTop = "10px";
          }(document, 'script', 'facebook-jssdk'));
    </script>
  </body>
</html>

app/views/news_feeds/_form.html.erb
<%= form_for(@news_feed) do |f| %>
  <% if @news_feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news_feed.errors.count, "error") %> prohibited this news_feed from being saved:</h2>

      <ul>
      <% @news_feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :host %><br />
    <%= f.text_field :host %>
  </div>
  <div class="field">
    <%= f.label :selector %><br />
    <%= f.text_field :selector %>
  </div>
  <div class="field">
    <%= f.label :url_pattern %><br />
    <%= f.text_field :url_pattern %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br />
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :image_source %><br />
    <%= f.text_field :image_source %>
  </div>
  <div class="field">
    <%= f.label :date_tag %><br />
    <%= f.text_field :date_tag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news_feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Host:</b>
  <%= @news_feed.host %>
</p>

<p>
  <b>Selector:</b>
  <%= @news_feed.selector %>
</p>

<p>
  <b>Url pattern:</b>
  <%= @news_feed.url_pattern %>
</p>

<p>
  <b>Title:</b>
  <%= @news_feed.title %>
</p>

<p>
  <b>Subtitle:</b>
  <%= @news_feed.subtitle %>
</p>

<p>
  <b>Image source:</b>
  <%= @news_feed.image_source %>
</p>

<p>
  <b>Date tag:</b>
  <%= @news_feed.date_tag %>
</p>

<fieldset>
  <%= link_to 'Edit', edit_news_feed_path(@news_feed) %> |
  <%= link_to 'Back', news_feeds_path %>
  <legend>Preview</legend>
  <ul>
    <% @news.each do |n| %>
      <li>
        <a href="<%= n.url %>" target="_blank">
          <% if n.image %>
            <img class="image-news" src="<%= n.image %>">
          <% end %>
          <% if n.title %>
            <span class="title-news"><%= n.title %></span>
          <% end %>
          <% if n.subtitle && n.subtitle != n.title %>
            <span class="title-news"><%= n.subtitle %></span>
          <% else %>
            <span class="subtitle-news"><%= n.subtitle %></span>
          <% end %>
        </a>
      </li>
    <% end %>
  </ul>
</fieldset>

app/views/timeline/index.html.erb
<ul id="featured_news" class="news left">
  <% @news.each do |n| %>
    <li class="featured">
      <a target="_blank" href="<%= n.url %>">
        <% if n.image %>
          <div class="featured-img-border">
            <img src="<%= n.image %>">
          </div>
        <% end %>
        <div class="<%= 'content-text-img' if n.image %>">
          <div class="featured-title">
            <%= n.title %>
          </div>
          <div class="featured-description">
            <%= n.subtitle %>
          </div>
          <div class="news-source"><%= n.feed.url %></div>
        </div>
      </a>
    </li>
  <% end %>
</ul>
<%= javascript_include_tag 'add2home' %>